# Generated by Django 5.1.7 on 2025-03-21 11:38

import borrowings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(default=borrowings.models.current_date),
        ),
    ]
